#!/busybox sh

/busybox mkdir /bin
/busybox --install /bin

#setsid cttyhack sh
mkdir /proc
mount -t proc proc /proc
mkdir /sys
mount -t sysfs sysfs /sys
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts
#echo /bin/mdev > /proc/sys/kernel/hotplug
mdev -s
mkdir -p /target
mount -t tmpfs -o size=4096m tmpfs /target 
echo "Extracting system image, please wait..."
xz -d -c -f /image.tar.xz | tar -x -f - -C /target
mount --move /sys /target/sys
mount --move /proc /target/proc
mount --move /dev /target/dev
exec switch_root /target /sbin/init

