#!/busybox sh

/busybox mkdir /bin
/busybox --install /bin

mkdir /proc
mount -t proc proc /proc
mkdir /sys
mount -t sysfs sysfs /sys
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts
mdev -s
setsid cttyhack sh

